// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

[TestFixture]
public class UntitledTest {
  
    private IWebDriver driver;
      public IDictionary<string, object> vars {get; private set;}
      private IJavaScriptExecutor js;

      [SetUp]
      public void SetUp() {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
      }

      [TearDown]
      protected void TearDown() {
        driver.Quit();
      }

      public string waitForWindow(int timeout) {
        try {
          Thread.Sleep(timeout);
        } catch(Exception e) {
          Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count) {
          return whNow.Except(whThen).First().ToString();
        } else {
          return whNow.First().ToString();
        }
      }

      [Test]
      public void untitled() {

        driver.Navigate().GoToUrl("https://www.endicia.com/login/");
        driver.Manage().Window.Size = new System.Drawing.Size(1462, 601);
        driver.FindElement(By.Id("main_1_txtAccountNumber")).Click();
        driver.FindElement(By.Id("main_1_txtAccountNumber")).SendKeys("955633");
        driver.FindElement(By.Id("main_1_txtPassword")).Click();
        driver.FindElement(By.Id("main_1_txtPassword")).SendKeys("Es9Jay9Es");
        driver.FindElement(By.CssSelector("#main_1_btnSubmit > span")).Click();
        driver.FindElement(By.LinkText("Reports")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.CssSelector("#actReportLogi_Row3 > span")).Click();
        driver.SwitchTo().Frame(0);
        driver.FindElement(By.Id("rbMonthYear_2")).Click();
        driver.FindElement(By.Id("selStartDate")).Click();
        driver.FindElement(By.Id("selStartDate")).Click();
        driver.FindElement(By.Id("selStartDate")).Clear();
        string varFechaInicio = DateTime.Today.AddDays(-6).ToString("MM/dd/yyyy");
        driver.FindElement(By.Id("selStartDate")).SendKeys(varFechaInicio);
        driver.FindElement(By.Id("selEndDate")).Click();
        driver.FindElement(By.Id("selEndDate")).Clear();
        string varFechaFin = DateTime.Today.ToString("MM/dd/yyyy");
        driver.FindElement(By.Id("selEndDate")).SendKeys(varFechaFin);
        driver.FindElement(By.Id("selStartDate")).Click();
        driver.FindElement(By.Id("btnExport")).Click();
        vars["WindowHandles"] = driver.WindowHandles;
        driver.FindElement(By.Id("btnExportExcel")).Click();
        vars["win5933"] = waitForWindow(2000);
        {
          var element = driver.FindElement(By.Id("btnExportExcel"));
          Actions builder = new Actions(driver);
          builder.MoveToElement(element).Perform();
        }
        {
          var element = driver.FindElement(By.TagName("body"));
          Actions builder = new Actions(driver);
          builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.SwitchTo().Window(vars["win5933"].ToString());
      }
}
