// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace UpsSelenium
{
    class GeneraLink
    {
        int Correlativo = 0;
        string Finaliza = "NO";
        string NombreAnterior = "";
        string RepitePaso = "NO";
        string FechaProceso     ="";
        string Fecha            ="";
        string fromFormat       ="";
        string varFechaInicio   ="";
        string varFechaFin      = "";
        DateTime fecha1         = DateTime.Now;
        DateTime fecha2         = DateTime.Now;
        DateTime fecha3         = DateTime.Now;
        string valorCampoOriginal = "";

        public void GeneraLinkGenerico(ref IWebDriver driver)
        {
            Correlativo = 0;
            
            try
            {
                for (int ii = 0; ii <= 9; ii++)
                {
                    string Proceso = ii.ToString();
                    ProcesoLink(ref driver, Proceso);

                    if(RepitePaso == "SI")
                    {
                        ii--;
                        RepitePaso = "NO";
                        driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
                    }

                    // SI
                    if (Finaliza == "SI") 
                    {
                        Finaliza = "NO";
                        break;
                    }
                }
            }
            catch(SystemException e)
            {
                Console.WriteLine(e.Message);
            }
            catch (NoSuchElementException e) 
            {
                Console.WriteLine(e.Message);
            }
            catch (StaleElementReferenceException e) 
            {
                Console.WriteLine(e.Message);
            }
            catch(WebDriverException e)
            {
                Console.WriteLine(e.Message);
            }
        }

        public void ObtieneFechasFactura(ref IWebDriver driver)
        {
            FechaProceso = "/html/body/div[2]/div[1]/div/div/div/form/table[2]/tbody/tr/td/table/tbody/tr/td/div/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/div/div/div/table/tbody/tr[2]/td/div/table[2]/tbody/tr/td[2]/div/table/tbody/tr[" + Correlativo + "]/td[4]/span";
            Fecha = driver.FindElement(By.XPath(FechaProceso)).Text;
            fromFormat = "MM/dd/yyyy";
            varFechaInicio = DateTime.Today.AddDays(-6).ToString("MM/dd/yyyy");
            varFechaFin = DateTime.Today.ToString("MM/dd/yyyy");
            fecha1 = DateTime.ParseExact(varFechaInicio, fromFormat, null);
            fecha2 = DateTime.ParseExact(varFechaFin, fromFormat, null);
            fecha3 = DateTime.ParseExact(Fecha, fromFormat, null);
        }

        public void GeneraLinkDescarga(ref IWebDriver driver, string Proceso)
        {
            // habilita boton de descarga
            // --------------------------
            driver.FindElement(By.Id("mainContentId:quickDownloadData")).Click();

            System.Threading.Thread.Sleep(2000);
            string xpathinput = "/html/body/div[2]/div[1]/div/div/div/form/table[2]/tbody/tr/td/table/tbody/tr/td/div/div/table/tbody/tr[1]/td/table/tbody/tr[5]/td/table/tbody/tr[3]/td/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[1]/td/div/table/tbody/tr[1]/td[2]/div/input";
            string valorCampo = driver.FindElement(By.XPath(xpathinput)).Text;

            string selectedValue = driver.FindElement(By.Id("mainContentId:newInvoiceNo")).FindElements(By.XPath("./option[@selected]"))[0].Text;

            System.Threading.Thread.Sleep(10000);

            // sustituyo el nombre el archivo
            // ------------------------------
            driver.FindElement(By.CssSelector(".iceInpTxt")).Click();
            //driver.FindElement(By.CssSelector(".iceInpTxt")).Clear();
            string NombreArchivo = "DF_" + Proceso;
            driver.FindElement(By.CssSelector(".iceInpTxt")).SendKeys(NombreArchivo);

            if (valorCampoOriginal != selectedValue)
            {
                driver.FindElement(By.Id("mainContentId:newInvoiceNo")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + valorCampoOriginal + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }

            string NombreActual = NombreArchivo;//driver.FindElement(By.CssSelector(".iceInpTxt")).Text;

            // si no cambia de nombre debe de repetir el paso
            // ----------------------------------------------
            if (NombreAnterior != NombreActual)
            {
                NombreAnterior = NombreArchivo; //driver.FindElement(By.CssSelector(".iceInpTxt")).Text;

                System.Threading.Thread.Sleep(2000);

                driver.FindElement(By.Id("mainContentId:fileTypequicksearch")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:fileTypequicksearch"));
                    dropdown.FindElement(By.XPath("//option[. = 'EXCEL (.xlsx)']")).Click();
                }

                System.Threading.Thread.Sleep(2000);

                driver.FindElement(By.Id("mainContentId:fileTypequicksearch")).Click();

                driver.FindElement(By.Id("mainContentId:templateTypequicksearch")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:templateTypequicksearch"));
                    dropdown.FindElement(By.XPath("//option[. = 'FedEx Standard Template']")).Click();
                }

                System.Threading.Thread.Sleep(5000);

                driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[2]/tbody/tr/td/table/tbody/tr/td/div/div/table/tbody/tr[1]/td/table/tbody/tr[5]/td/table/tbody/tr[3]/td/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/table/tbody/tr[5]/td/div/table/tbody/tr[2]/td/div/div/input[2]")).Click();

                System.Threading.Thread.Sleep(15000);

                driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            else
            {
                RepitePaso = "SI";
            }

        }

        public void ProcesoLink(ref IWebDriver driver, string Proceso)
        {
            //driver.FindElement(By.Id("mainContentId:newAccount1")).Click();

            System.Threading.Thread.Sleep(10000);

            // verifica si debe de descargar la factura si pertenece al rango de fechas
            // -------------------------------------------------------------------------
            Correlativo += 1;
            try
            {
                ObtieneFechasFactura(ref driver);
            }
            catch (SystemException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
                System.Threading.Thread.Sleep(2000);
                ObtieneFechasFactura(ref driver);
            }
            catch (NoSuchElementException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
                System.Threading.Thread.Sleep(2000);
                ObtieneFechasFactura(ref driver);
            }
            catch (StaleElementReferenceException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
                System.Threading.Thread.Sleep(2000);
                ObtieneFechasFactura(ref driver);
            }
            catch (WebDriverException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
                System.Threading.Thread.Sleep(2000);
                ObtieneFechasFactura(ref driver);
            }

            if ((fecha3 >= fecha1) && (fecha3 <= fecha2))
            {

                string inputoriginal = "/html/body/div[2]/div[1]/div/div/div/form/table[2]/tbody/tr/td/table/tbody/tr/td/div/div/table/tbody/tr[2]/td/div/table/tbody/tr/td/div/div/div/table/tbody/tr[2]/td/div/table[2]/tbody/tr/td[2]/div/table/tbody/tr["+ Correlativo + "]/td[2]/a";

                valorCampoOriginal = driver.FindElement(By.XPath(inputoriginal)).Text;

                // selecciona la primer fila para descargar la factura
                // ----------------------------------------------------
                string facturaProceso = "mainContentId:invoicesAllOpenTable:" + Proceso + ":invoiceLinkAllOpen";
                driver.FindElement(By.Id(facturaProceso)).Click();

                try
                {
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                }
                catch (WebDriverException e)
                {
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                }

                System.Threading.Thread.Sleep(2000);

                try
                {
                    GeneraLinkDescarga(ref driver, Proceso);
                }
                catch (SystemException e)
                {
                    Console.WriteLine(e.Message);
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                    System.Threading.Thread.Sleep(2000);
                    GeneraLinkDescarga(ref driver, Proceso);
                }
                catch (NoSuchElementException e)
                {
                    Console.WriteLine(e.Message);
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                    System.Threading.Thread.Sleep(2000);
                    GeneraLinkDescarga(ref driver, Proceso);
                }
                catch (StaleElementReferenceException e)
                {
                    Console.WriteLine(e.Message);
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                    System.Threading.Thread.Sleep(2000);
                    GeneraLinkDescarga(ref driver, Proceso);
                }
                catch (WebDriverException e)
                {
                    Console.WriteLine(e.Message);
                    driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/invoiceDetailFBO.xhtml");
                    System.Threading.Thread.Sleep(2000);
                    GeneraLinkDescarga(ref driver, Proceso);
                }
            }
            else
            {
                Finaliza = "SI";
            }
        }
    }
}
