// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Configuration;


namespace UpsSelenium
{
    [TestFixture]
    public class GeneraLinkFedexTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        GeneraLink GeneraLinkObj = new GeneraLink();
        RealizaDescarga RealizaDescargaObj = new RealizaDescarga();

        string Cuenta = "";
        [SetUp]
        public void SetUp()
        {
            //Create a chrome options object
            //var chromeOptions = new ChromeOptions();
            ////Create a new proxy object
            //var proxy = new Proxy();
            ////Set the http proxy value, host and port.
            //proxy.HttpProxy = "195.154.119.202:443";
            ////Set the proxy to the Chrome options
            //chromeOptions.Proxy = proxy;
            ////Then create a new ChromeDriver passing in the options
            ////ChromeDriver path isn't required if its on your path
            ////If it now downloaded it and put the path here
            //var Driver = new ChromeDriver(@"C:\Users\ANTONIO\Documents\Trabajo\Mis Proyectos\FedexSelenium\FedexSelenium\bin\Debug\", chromeOptions);
            ChromeDriverService service = ChromeDriverService.CreateDefaultService(@"C:\Users\ANTONIO\Documents\Trabajo\Mis Proyectos\FedexSelenium\FedexSelenium\bin\Debug\");
            service.Port = 555;
            IWebDriver Driver = new ChromeDriver(service);
            //Navigation to a url and a look at the traffic logged in fiddler
            Driver.Navigate().GoToUrl("https://whatismyipaddress.com/");

            //driver = new ChromeDriver();
            //js = (IJavaScriptExecutor)driver;
            //vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        [Test]
        public void generaLinkFedex()
        {
            // realiza logeo
            // -------------
            RealizaLogon();
            
            // genera links de las cuenta
            // ---------------------------
            Cuenta = "6306-7664-9";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "6534-1898-1";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "6619-1081-0";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "6619-1195-6";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "9258-7381-0";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "9260-3201-1";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "9269-6837-8";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "9837-2911-8";
            GeneraLinCuentas(Cuenta);
            
            Cuenta = "9876-4319-6";
            GeneraLinCuentas(Cuenta);
            
            // espera media hora para que se generen todos los links
            // -----------------------------------------------------
            Console.WriteLine("Comienza la espera de media hora para dar tiempo de la generacion de los archivos");
            System.Threading.Thread.Sleep(1800000);
            Console.WriteLine("Continua El proceso ya descargando links generados");

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();
            
            // Descarga Archivos
            // -----------------
            Cuenta = "6306-7664-9";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "6534-1898-1";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "6619-1081-0";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "6619-1195-6";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "9258-7381-0";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "9260-3201-1";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "9269-6837-8";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "9837-2911-8";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();
            System.Threading.Thread.Sleep(5000);

            // realiza logeo de nuevo ya que al esperar los 30 minutos se finaliza la session
            // -------------
            RealizaLogon();

            Cuenta = "9876-4319-6";
            RealizaDescarga(Cuenta);
            driver.FindElement(By.XPath("/html/body/div[2]/div[1]/div/div/div/form/table[1]/tbody/tr/td[2]/div/table/tbody/tr/td[6]/div/table/tbody/tr/td[1]/div/div[1]/a/span")).Click();

        }

        // RealizaDescarga de los links
        // ----------------------------
        public void RealizaDescarga(string Cuenta)
        {
            driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");
            System.Threading.Thread.Sleep(5000);

            // Cambia la cuenta a descargar
            // ----------------------------
            driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
            {
                var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                string xpathstring = "//option[. = '" + Cuenta + "']";
                dropdown.FindElement(By.XPath(xpathstring)).Click();
            }

            System.Threading.Thread.Sleep(5000);

            driver.Navigate().GoToUrl("https://www.fedex.com//fedexbillingonline/pages/searchanddownload/downloadCenter.xhtml");

            System.Threading.Thread.Sleep(5000);

            // genera link
            // -----------
            RealizaDescargaObj.DescargaLinkGenerico(ref driver);

            System.Threading.Thread.Sleep(10000);

            driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();

            System.Threading.Thread.Sleep(5000);
        }

        // genera links de las cuenta
        // ---------------------------
        public void GeneraLinCuentas(string Cuenta)
        {
            try
            {
                // Cambia la cuenta a descargar
                // ----------------------------
                driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + Cuenta + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }
            catch (SystemException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");

                // Cambia la cuenta a descargar
                // ----------------------------
                driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + Cuenta + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }
            catch (NoSuchElementException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");

                // Cambia la cuenta a descargar
                // ----------------------------
                driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + Cuenta + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }
            catch (StaleElementReferenceException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");

                // Cambia la cuenta a descargar
                // ----------------------------
                driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + Cuenta + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }
            catch (WebDriverException e)
            {
                Console.WriteLine(e.Message);
                driver.Navigate().GoToUrl("https://www.fedex.com/fedexbillingonline/pages/accountsummary/accountSummaryFBO.xhtml");

                // Cambia la cuenta a descargar
                // ----------------------------
                driver.FindElement(By.Id("mainContentId:newAccount1")).Click();
                {
                    var dropdown = driver.FindElement(By.Id("mainContentId:newAccount1"));
                    string xpathstring = "//option[. = '" + Cuenta + "']";
                    dropdown.FindElement(By.XPath(xpathstring)).Click();
                }
            }


            // genera link
            // -----------
            GeneraLinkObj.GeneraLinkGenerico(ref driver);

            System.Threading.Thread.Sleep(10000);

            try
            {
                driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            catch (SystemException e)
            {
                Console.WriteLine(e.Message);
                driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            catch (NoSuchElementException e)
            {
                Console.WriteLine(e.Message);
                driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            catch (StaleElementReferenceException e)
            {
                Console.WriteLine(e.Message);
                 driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            catch (WebDriverException e)
            {
                Console.WriteLine(e.Message);
                 driver.FindElement(By.Id("mainContentId:accSmyCmdLink")).Click();
            }
            System.Threading.Thread.Sleep(5000);
        }

        // Realiza Logon
        // -------------
        public void RealizaLogon()
        {
            try
            {
                driver.Navigate().GoToUrl("https://www.fedex.com/en-us/home.html");

                driver.FindElement(By.CssSelector(".fxg-user-options__sign-in-text")).Click();

                string Usuario = ConfigurationManager.AppSettings["UsrFedex"];

                driver.FindElement(By.Id("NavLoginUserId")).Click();
                driver.FindElement(By.Id("NavLoginUserId")).SendKeys(Usuario);


                string PassWord = ConfigurationManager.AppSettings["PassFedex"];
                driver.FindElement(By.Id("NavLoginPassword")).Click();
                driver.FindElement(By.Id("NavLoginPassword")).SendKeys(PassWord);

                driver.FindElement(By.CssSelector(".fdx-login_error-label-change")).Click();

                driver.FindElement(By.CssSelector(".fxg-user-options__sign-in-text")).Click();
                driver.FindElement(By.LinkText("View & Pay Bill")).Click();
            }
            catch (SystemException e)
            {
                driver.Navigate().GoToUrl("https://www.fedex.com/en-us/home.html");

                string Usuario = ConfigurationManager.AppSettings["UsrFedex"];
                driver.FindElement(By.Name("NavLoginUserId")).Click();
                driver.FindElement(By.Name("NavLoginUserId")).SendKeys(Usuario);

                string PassWord = ConfigurationManager.AppSettings["PassFedex"];
                driver.FindElement(By.Name("NavLoginPassword")).Click();
                driver.FindElement(By.Name("NavLoginPassword")).SendKeys(PassWord);

                driver.FindElement(By.XPath("/html/body/div[1]/header/div/div/nav/div/div/div[1]/div[1]/div/div/form/button")).Click();
            }
            catch (NoSuchElementException e)
            {
                driver.Navigate().GoToUrl("https://www.fedex.com/en-us/home.html");

                string Usuario = ConfigurationManager.AppSettings["UsrFedex"];

                driver.FindElement(By.Id("NavLoginUserId")).Click();
                driver.FindElement(By.Name("NavLoginUserId")).SendKeys(Usuario);


                string PassWord = ConfigurationManager.AppSettings["PassFedex"];
                driver.FindElement(By.Id("NavLoginPassword")).Click();
                driver.FindElement(By.Name("NavLoginPassword")).SendKeys(PassWord);

                driver.FindElement(By.CssSelector(".fdx-login_error-label-change")).Click();

                driver.FindElement(By.CssSelector(".fxg-user-options__sign-in-text")).Click();
                driver.FindElement(By.LinkText("View & Pay Bill")).Click();
            }
            catch (StaleElementReferenceException e)
            {
                driver.Navigate().GoToUrl("https://www.fedex.com/en-us/home.html");

                driver.FindElement(By.Name("NavLoginUserId")).Click();
                driver.FindElement(By.Name("NavLoginUserId")).SendKeys("sjscommercial9500");

                driver.FindElement(By.Name("NavLoginPassword")).Click();
                driver.FindElement(By.Name("NavLoginPassword")).SendKeys("Sjs123456");

                driver.FindElement(By.XPath("/html/body/div[1]/header/div/div/nav/div/div/div[1]/div[1]/div/div/form/button")).Click();
            }
            catch (WebDriverException e)
            {
                driver.Navigate().GoToUrl("https://www.fedex.com/en-us/home.html");

                driver.FindElement(By.Name("NavLoginUserId")).Click();
                driver.FindElement(By.Name("NavLoginUserId")).SendKeys("sjscommercial9500");

                driver.FindElement(By.Name("NavLoginPassword")).Click();
                driver.FindElement(By.Name("NavLoginPassword")).SendKeys("Sjs123456");

                driver.FindElement(By.XPath("/html/body/div[1]/header/div/div/nav/div/div/div[1]/div[1]/div/div/form/button")).Click();
            }

        }
    }
}
